// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_vehiclelist

import (
	models "afry-toll-calculator/models"

	mock "github.com/stretchr/testify/mock"
)

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// GetVehicleList provides a mock function with no fields
func (_m *MockGetter) GetVehicleList() []models.Vehicle {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVehicleList")
	}

	var r0 []models.Vehicle
	if rf, ok := ret.Get(0).(func() []models.Vehicle); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Vehicle)
		}
	}

	return r0
}

// MockGetter_GetVehicleList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVehicleList'
type MockGetter_GetVehicleList_Call struct {
	*mock.Call
}

// GetVehicleList is a helper method to define mock.On call
func (_e *MockGetter_Expecter) GetVehicleList() *MockGetter_GetVehicleList_Call {
	return &MockGetter_GetVehicleList_Call{Call: _e.mock.On("GetVehicleList")}
}

func (_c *MockGetter_GetVehicleList_Call) Run(run func()) *MockGetter_GetVehicleList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGetter_GetVehicleList_Call) Return(_a0 []models.Vehicle) *MockGetter_GetVehicleList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetter_GetVehicleList_Call) RunAndReturn(run func() []models.Vehicle) *MockGetter_GetVehicleList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
