// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_fee

import (
	models "afry-toll-calculator/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetFee provides a mock function with given fields: vehicleType, entryDates
func (_m *MockService) GetFee(vehicleType models.VehicleType, entryDates []time.Time) (int, error) {
	ret := _m.Called(vehicleType, entryDates)

	if len(ret) == 0 {
		panic("no return value specified for GetFee")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(models.VehicleType, []time.Time) (int, error)); ok {
		return rf(vehicleType, entryDates)
	}
	if rf, ok := ret.Get(0).(func(models.VehicleType, []time.Time) int); ok {
		r0 = rf(vehicleType, entryDates)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(models.VehicleType, []time.Time) error); ok {
		r1 = rf(vehicleType, entryDates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetFee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFee'
type MockService_GetFee_Call struct {
	*mock.Call
}

// GetFee is a helper method to define mock.On call
//   - vehicleType models.VehicleType
//   - entryDates []time.Time
func (_e *MockService_Expecter) GetFee(vehicleType interface{}, entryDates interface{}) *MockService_GetFee_Call {
	return &MockService_GetFee_Call{Call: _e.mock.On("GetFee", vehicleType, entryDates)}
}

func (_c *MockService_GetFee_Call) Run(run func(vehicleType models.VehicleType, entryDates []time.Time)) *MockService_GetFee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.VehicleType), args[1].([]time.Time))
	})
	return _c
}

func (_c *MockService_GetFee_Call) Return(_a0 int, _a1 error) *MockService_GetFee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetFee_Call) RunAndReturn(run func(models.VehicleType, []time.Time) (int, error)) *MockService_GetFee_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
