// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_holidays

import mock "github.com/stretchr/testify/mock"

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: year
func (_m *MockGetter) Get(year int) ([]string, error) {
	ret := _m.Called(year)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return rf(year)
	}
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - year int
func (_e *MockGetter_Expecter) Get(year interface{}) *MockGetter_Get_Call {
	return &MockGetter_Get_Call{Call: _e.mock.On("Get", year)}
}

func (_c *MockGetter_Get_Call) Run(run func(year int)) *MockGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockGetter_Get_Call) Return(_a0 []string, _a1 error) *MockGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetter_Get_Call) RunAndReturn(run func(int) ([]string, error)) *MockGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
