// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_pricelist

import (
	pricelist "afry-toll-calculator/services/pricelist"

	mock "github.com/stretchr/testify/mock"
)

// MockPriceBlockGetter is an autogenerated mock type for the PriceBlockGetter type
type MockPriceBlockGetter struct {
	mock.Mock
}

type MockPriceBlockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceBlockGetter) EXPECT() *MockPriceBlockGetter_Expecter {
	return &MockPriceBlockGetter_Expecter{mock: &_m.Mock}
}

// GetPriceBlocks provides a mock function with no fields
func (_m *MockPriceBlockGetter) GetPriceBlocks() []pricelist.PriceBlock {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPriceBlocks")
	}

	var r0 []pricelist.PriceBlock
	if rf, ok := ret.Get(0).(func() []pricelist.PriceBlock); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pricelist.PriceBlock)
		}
	}

	return r0
}

// MockPriceBlockGetter_GetPriceBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceBlocks'
type MockPriceBlockGetter_GetPriceBlocks_Call struct {
	*mock.Call
}

// GetPriceBlocks is a helper method to define mock.On call
func (_e *MockPriceBlockGetter_Expecter) GetPriceBlocks() *MockPriceBlockGetter_GetPriceBlocks_Call {
	return &MockPriceBlockGetter_GetPriceBlocks_Call{Call: _e.mock.On("GetPriceBlocks")}
}

func (_c *MockPriceBlockGetter_GetPriceBlocks_Call) Run(run func()) *MockPriceBlockGetter_GetPriceBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPriceBlockGetter_GetPriceBlocks_Call) Return(_a0 []pricelist.PriceBlock) *MockPriceBlockGetter_GetPriceBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPriceBlockGetter_GetPriceBlocks_Call) RunAndReturn(run func() []pricelist.PriceBlock) *MockPriceBlockGetter_GetPriceBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPriceBlockGetter creates a new instance of MockPriceBlockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceBlockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceBlockGetter {
	mock := &MockPriceBlockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
