// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_models

import (
	models "afry-toll-calculator/models"

	mock "github.com/stretchr/testify/mock"
)

// MockVehicle is an autogenerated mock type for the Vehicle type
type MockVehicle struct {
	mock.Mock
}

type MockVehicle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVehicle) EXPECT() *MockVehicle_Expecter {
	return &MockVehicle_Expecter{mock: &_m.Mock}
}

// GetType provides a mock function with no fields
func (_m *MockVehicle) GetType() models.VehicleType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 models.VehicleType
	if rf, ok := ret.Get(0).(func() models.VehicleType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.VehicleType)
	}

	return r0
}

// MockVehicle_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type MockVehicle_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *MockVehicle_Expecter) GetType() *MockVehicle_GetType_Call {
	return &MockVehicle_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *MockVehicle_GetType_Call) Run(run func()) *MockVehicle_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVehicle_GetType_Call) Return(_a0 models.VehicleType) *MockVehicle_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVehicle_GetType_Call) RunAndReturn(run func() models.VehicleType) *MockVehicle_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// IsTollFree provides a mock function with no fields
func (_m *MockVehicle) IsTollFree() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTollFree")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockVehicle_IsTollFree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTollFree'
type MockVehicle_IsTollFree_Call struct {
	*mock.Call
}

// IsTollFree is a helper method to define mock.On call
func (_e *MockVehicle_Expecter) IsTollFree() *MockVehicle_IsTollFree_Call {
	return &MockVehicle_IsTollFree_Call{Call: _e.mock.On("IsTollFree")}
}

func (_c *MockVehicle_IsTollFree_Call) Run(run func()) *MockVehicle_IsTollFree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVehicle_IsTollFree_Call) Return(_a0 bool) *MockVehicle_IsTollFree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVehicle_IsTollFree_Call) RunAndReturn(run func() bool) *MockVehicle_IsTollFree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVehicle creates a new instance of MockVehicle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVehicle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVehicle {
	mock := &MockVehicle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
